carts/urls.py
from django.urls import path,include

from .views import viewcart,add_to_cart,remove_from_cart,remove_single_item_from_cart,checkout

urlpatterns = [
    path('',viewcart,name="cart-view"),
    path('add/<slug>',add_to_cart,name="add_to_cart"),
    path('remove/<slug>',remove_from_cart,name="remove_from_cart"),
    path('remove_singe_item/<slug>',remove_single_item_from_cart,name="remove_single_item_from_cart") ,
    path('checkout',checkout,name="checkout")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('carts/',include('carts.urls'))    
] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path,include
from .views import home,productlist,ProductDetailView,SearchResultView
urlpatterns = [
    
    # path('',  ProductListView.as_view() ,name="home"),
    path('',home,name="home"),
    path('products', productlist, name="product-list" ),
    path('product/<slug>', ProductDetailView.as_view(),name="product-detail"),
    path('search/',SearchResultView.as_view(),name="search-result")
]

carts/models.py
from django.db import models
from django.contrib.auth.models import User

from django_countries.fields import CountryField

from products.models import Product

from cities_light.models import City



class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)

def __str__(self):
    return self.name


class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)

    def __str__(self):
        return f'{self.quantity} of {self.product.title}'
    
    def get_total_item_price(self):
        return self.quantity * self.product.price
    
    def get_total_item_discount_price(self):
        return self.quantity * self.product.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_item_discount_price()
   
    def get_final_price(self):
        if self.product.discount_price:
            return self.get_total_item_discount_price()
        return self.get_total_item_price()


class Cart(models.Model):
    customer = models.ForeignKey('Customer',on_delete=models.CASCADE,null=True,blank=True)
    cartitem = models.ManyToManyField(CartItem)
    total = models.DecimalField(max_digits=100,decimal_places=2,default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active = models.BooleanField(default=True)
    ordered = models.BooleanField(default=False)
    shipping_adress = models.ForeignKey('Adress',on_delete=models.CASCADE,blank=True,null=True,related_name='shipping_adress')
    billing_adress = models.ForeignKey('Adress',on_delete=models.CASCADE,blank=True,null=True,related_name='billing_adress')
    

    def __str__(self):
        return f'{self.id}'
    

    def get_total(self):
        total = 0
        for cart_item in self.cartitem.all():
            total += cart_item.get_final_price()
        return total  
    
    def total_qantity(self):
        totalQuantity = 0
        for cart_item in self.cartitem.all():
            totalQuantity += cart_item.quantity
        return totalQuantity


ADRESS_FIELDS = (
    ('B','Billing'),
    ('S', 'Shipping')
)


class Adress(models.Model):
    customer = models.ForeignKey('Customer',on_delete=models.CASCADE)
    street_adress = models.CharField(max_length=100)
    apartment_adress = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    city = models.ForeignKey(City,on_delete=models.CASCADE,blank=True, null=True)
    zip_code = models.CharField(max_length=100)
    adress_type = models.CharField(choices=ADRESS_FIELDS,max_length=1)

    class Meta:
        verbose_name_plural = 'Adresses'

products/models.py
from django.urls import reverse
from django.db import models
from PIL import Image
from django.db.models import Q
from django.contrib.auth.models import User





CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)
LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)



class Product(models.Model):
    title = models.CharField(max_length=120,null=False,blank=False)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(decimal_places=2,max_digits=100, default=29.99)
    discount_price = models.DecimalField(decimal_places=2,max_digits=100,null=True,blank=True)
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=2,default="S")
    label = models.CharField(choices = LABEL_CHOICES,max_length=1,null=True,blank=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to="products/images",default="products/placeholder.png")

    def __str__(self):
        return self.title

    # def save(self,*args,**kwargs):
    # #run to save method parent class
    #     super().save(*args,**kwargs)
    #     img = Image.open(self.image.path)
    #     if  not self.featured:
    #         output_size = (90,60)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)
    #     else:
    #         output_size = (300,300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)
    
    def get_price(self):
        return self.price
    
    class Meta:
        unique_together = ['title','slug']
    
    def get_absolute_url(self):
        return reverse("product-detail", kwargs={"slug": self.slug})
        # return reverse('product-detail',args=[self.slug])
    

    
    """ auto_now_add True ise kaydedildiğinde tarih giriyor
    auto_now False ise update edildiğinde tarihi değiştirmiyor
    o yüzden updated alanında auto_now True oldu """



  



    

products/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic.detail import BaseDetailView
from django.http import JsonResponse
from django.views.generic import ListView,DetailView


from .models import Product
from carts.models import Cart,CartItem



from django.db.models import Q

def home(request):
    products = Product.objects.all()
    context = {'products':products}
    return render(request,"products/home.html",context)

def productlist(request):
    products = Product.objects.all()
    context = {'products':products}
    return render(request,"products/product_list.html",context)

class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = "products/product_detail.html"



    


class SearchResultView(ListView):
    model = Product
    template_name = 'products/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get('q') 
        object_list = Product.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
        return object_list



# class ProductListView(ListView):
#     model = Product
#     template_name = 'products/home.html'

templates/products/home.html
{% extends 'base.html' %}
{%  load static %}


{% block title %} Ecommerce-Home {% endblock title %}
{% block content %}


<main>
  <section id="searchSection">

    <div class="container-fluid pt-5 mt-5">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 ">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form action="{% url 'search-result' %}" method="get" class="form-inline">
            <div class="md-form my-0">
              <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>

  </section>
      <!--Navbar-->
      
    </section>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="container pt-3">
        <div class="row wow fadeIn">

            {% for product in products %}
          <div class="col-lg-3 col-md-6 mb-4 border-0">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ product.image.url }}" class="card-img-top img-fluid home-product-image"
                  alt="">
                <a href="{{  product.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{  product.get_absolute_url }}" class="grey-text">
                  <h5>{{product.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{  product.get_absolute_url }}" class="dark-grey-text">{{ product.title }}
                      <span class="badge badge-pill    {{ product.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  {% if product.discount_price %}
                  <strong>{{product.discount_price}}$</strong>
                  {% else %}
                  <strong>{{product.price}}$</strong>
                  {% endif %}
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
            {% endfor %}
        
        </div>
        <!--Grid row-->

      </div> 

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>



{% endblock %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="{{ product.image.url  }}" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{product.get_category_display}}</span>
            </a>
            <a href="">
              <span class="badge blue mr-1">{{product.get_label_display}}</span>
            </a>
          </div>
          
        <div class="cart float-right">
          {{product.cartitem_set.all}}
          <button data-slug={{product.slug}} data-url='{% url "add_to_cart"  product.slug %}'  id="addButton" class="btn
          {%if product.cartitem_set.all%}
          
          btn-success 
          {% else %}
          btn-danger
          {% endif %}
          btn-md my-0 p">
          {%if product.cartitem_set.all%}
            Added To Cart
          {% else %}
          Add to Cart
          {% endif %}
            <i class="fas fa-shopping-cart ml-1"></i>
            {{message }}
        </button>
        </div>  

       
        
          <p class="lead">

            <span class="mr-1">
              {% if product.discount_price %}
              <del>${{ product.price }}</del>
            </span>
            <span>${{product.discount_price}}</span>
            {% else %}
            <span>${{product.price}}</span>
            {% endif %}
          </p>

          <p class="lead font-weight-bold">{{product.title}}</p>

          <p>{{ product.description }}</p>
          </form>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>W


  </div>
</main>

<script>

$(document).on('click', '#addButton', function () {
    const addButton =  $("#addButton")
    const url = addButton.attr("data-url");
    const slug = addButton.attr('data-slug');
    $.ajax({
      url:url,
      data:{
        slug:slug
      },
      success:function(response){
        console.log(response);
        if(response.isCartInTheProduct){
          addButton.html('Added to Cart <i class="fas fa-shopping-cart ml-1"></i>')
          addButton.removeClass().addClass("btn btn-success btn-md my-0 p")
        }else{
          addButton.html('Add to Cart <i class="fas fa-shopping-cart ml-1"></i>')
          addButton.removeClass().addClass("btn btn-danger btn-md my-0 p")

        }

      }
    })
});





 
</script>


<script></script>
{% endblock %}

templates/products/product_list.html
{% extends 'base.html' %}
{%  block content %}
{% load static %}



<!-- 
<div class="container">
    <div class="row">
        {%  for product in products %}
        <div class="col-sm-4">
            
            <div class="thumbnail">
               {% if product.productimage_set.all %}
                {%  for item in product.productimage_set.all %}
              
                <img class="img-fluid" src="{{ item.image.url }}">  
    
                {% endfor %}
                {% else %}
                <img src="{%   static 'img/default.jpg'%}" alt="">
                {% endif %}
                <div class="caption">
                <h3><a href="{{  product.get_absolute_url }}">{{  product.title  }}</a></h3>
                <p>{{ product.description|truncatewords:2 }}</p>
                <p><a href="" class=" btn btn-primary" role="button">View</a><a href="" class="btn btn-default">Button</a></p>
                </div>
            </div>
       
        </div>
        {% endfor %}
    </div>
</div> -->


<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="md-4">
        <div class="card mb-4">
            {% if product.productimage_set.all %}
                {%  for item in product.productimage_set.all %}
            <img src="#" alt="card-img-top img-fluid">
            {% endfor %}
            {% else %}
                <img src="{%   static 'img/default.jpg'%}" alt="">
            {% endif %}
            <div class="card-body">
                <h3 class="card-title">{{ product.title }}</h3>
                <p class="text-muted card-text">{{ product.description|truncatewords:3 }}</p>
            </div>
        </div>

        </div>
        {% endfor %}
    </div>
</div>


{%  endblock content %}

templates/products/search_result.html
{% extends 'base.html' %}

{% block content %}
{% load static %}


  <section id="searchSection">

    <div class="container-fluid pt-5 mt-5">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 ">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form action="{% url 'search-result' %}" method="get" class="form-inline">
            <div class="md-form my-0">
              <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>

  </section>

<!--Section: Products v.3-->
<section class="text-center mb-4">

  <div class="container pt-3">
  <div class="row wow fadeIn">

      {% for product in object_list %}
    <div class="col-lg-3 col-md-6 mb-4">

      <!--Card-->
      <div class="card">

        <!--Card image-->
        <div class="view overlay">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
            alt="">
          <a href="{{  product.get_absolute_url }}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
        <!--Card image-->

        <!--Card content-->
        <div class="card-body text-center">
          <!--Category & Title-->
          <a href="{{  product.get_absolute_url }}" class="grey-text">
            <h5>{{product.get_category_display}}</h5>
          </a>
          <h5>
            <strong>
              <a href="{{  product.get_absolute_url }}" class="dark-grey-text">{{ product.title }}
                <span class="badge badge-pill    {{ product.get_label_display }}-color">NEW</span>
              </a>
            </strong>
          </h5>

          <h4 class="font-weight-bold blue-text">
            <strong>{{product.price}}$</strong>
          </h4>

        </div>
        <!--Card content-->

      </div>
      <!--Card-->

    </div>
      {% endfor %}
  
  </div>
  <!--Grid row-->

</div> 

</section>
{% endblock content %}